version: '3.8'

networks:
  internet-store:

services:
  dev-db:
    image: mongo
    container_name: dev-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=dev-db
    networks:
      - internet-store
